class_name Room
extends Node2D
## A single delve room. Generated by tools/gen_rooms.gd from the ASCII maps in
## tools/rooms/room_layouts.gd — edit the maps, not these scenes.
##
## A room knows its own geometry, entry, exit and spawn points, and nothing about
## the delve it sits in. The Delve places the player and drives transitions; the
## room just answers questions. That keeps rooms reusable in any order, which is
## the whole point of assembling them from a seed.

## Emitted when the player reaches the exit. The Delve listens; the room does not
## know what happens next.
signal exit_reached

@export var room_id: String = ""
@export var room_size: Vector2 = Vector2.ZERO

## Radius around the exit marker that counts as reaching it.
@export var exit_radius: float = 42.0

var _player: Player = null
var _fired: bool = false

@onready var entry: Marker2D = $Entry
@onready var exit_marker: Marker2D = $Exit
@onready var spawns: Node2D = $Spawns


func _ready() -> void:
	_player = get_tree().get_first_node_in_group(&"player") as Player


## Spawn points, as {kind, position}. The Delve decides what to build from them,
## so rooms stay ignorant of the enemy roster.
func spawn_points() -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for child: Node in spawns.get_children():
		var marker: Marker2D = child as Marker2D
		if marker == null:
			continue
		out.append({
			"kind": String(marker.get_meta(&"kind", "grunt")),
			"position": marker.global_position,
		})
	return out


func entry_position() -> Vector2:
	return entry.global_position


func exit_position() -> Vector2:
	return exit_marker.global_position


func _physics_process(_delta: float) -> void:
	if _fired or _player == null:
		return
	if _player.global_position.distance_to(exit_marker.global_position) > exit_radius:
		return
	# Fire once. The delve frees this room, but a second emission in the same
	# frame would advance two rooms at once.
	_fired = true
	exit_reached.emit()
