class_name Room
extends Node2D
## A single delve room. Generated by tools/gen_rooms.gd from the ASCII maps in
## tools/rooms/room_layouts.gd — edit the maps, not these scenes.
##
## A room knows its own geometry, entry, exit and spawn points, and nothing about
## the delve it sits in. The Delve places the player and drives transitions; the
## room just answers questions. That keeps rooms reusable in any order, which is
## the whole point of assembling them from a seed.

## The player entered or left the exit zone. The run coordinator listens and puts
## up the extract/descend choice — the room itself makes no decision, it only
## reports where the player is standing.
signal exit_zone_changed(inside: bool)

@export var room_id: String = ""
@export var room_size: Vector2 = Vector2.ZERO

## Radius around the exit marker that counts as reaching it.
@export var exit_radius: float = 42.0

@export_group("Exit marker")
## The exit was an invisible trigger, so a cleared room looked like a dead end —
## you could kill everything and have no idea where to go. It reads as a warm
## SHAFT OF SURFACE LIGHT with a real glow: "up = out = light" made literal, so
## it fits the graded dark instead of fighting it the way the old mint rect did.
@export var exit_colour: Color = Color(1.0, 0.83, 0.48)
@export var exit_size: Vector2 = Vector2(46, 150)
@export var exit_pulse_hz: float = 1.2

var _player: Player = null
var _in_exit_zone: bool = false
var _pulse: float = 0.0
var _exit_shaft: Sprite2D = null
var _exit_light: PointLight2D = null

@onready var entry: Marker2D = $Entry
@onready var exit_marker: Marker2D = $Exit
@onready var spawns: Node2D = $Spawns


## Built in code rather than baked into the generated scenes, so changing how the
## exit reads does not mean regenerating every room.
func _ready() -> void:
	# The shaft: a soft warm column, brightest at the floor where you stand to
	# extract, fading up into the dark like light spilling down from the surface.
	_exit_shaft = Sprite2D.new()
	_exit_shaft.texture = _shaft_texture()
	_exit_shaft.modulate = exit_colour
	_exit_shaft.centered = false
	_exit_shaft.position = Vector2(-exit_size.x * 0.5, -exit_size.y)
	_exit_shaft.scale = exit_size / Vector2(32, 128)
	exit_marker.add_child(_exit_shaft)

	# A real light so the exit glows a pool onto the surrounding rock — a beacon
	# across a dark room, which is the whole point of drawing it.
	_exit_light = PointLight2D.new()
	_exit_light.texture = _glow_texture()
	_exit_light.color = exit_colour
	_exit_light.energy = 1.2
	_exit_light.texture_scale = 2.4
	_exit_light.position = Vector2(0, -exit_size.y * 0.4)
	exit_marker.add_child(_exit_light)

	_build_dressing.call_deferred()
	_build_glints.call_deferred()


## Ore glints: a rare white sparkle on ORE tiles, so a vein catches the eye and
## "there is value in this rock" reads without a label. Deterministic — the
## phase is the cell hash, animated over wall-clock (visual only), never Rng.
const ORE_ATLAS: Vector2i = Vector2i(2, 0)
const ORE_RICH_ATLAS: Vector2i = Vector2i(6, 0)
## Cap so an ore-rich hall does not strobe.
@export var glint_max: int = 12

var _glints: Array[Sprite2D] = []
var _glint_phase: Array[float] = []


func _build_glints() -> void:
	var tiles: TileMapLayer = get_node_or_null(^"Tiles") as TileMapLayer
	if tiles == null:
		return
	var tex: ImageTexture = _glint_texture()
	for cell: Vector2i in tiles.get_used_cells():
		if _glints.size() >= glint_max:
			break
		var atlas: Vector2i = tiles.get_cell_atlas_coords(cell)
		if atlas != ORE_ATLAS and atlas != ORE_RICH_ATLAS:
			continue
		# Only a fraction of veins glint, so it stays rare, not a light show.
		var h: int = _cell_hash(cell.x + 41, cell.y + 17)
		if h % 100 >= 45:
			continue
		var glint: Sprite2D = Sprite2D.new()
		glint.texture = tex
		glint.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		glint.position = tiles.map_to_local(cell)
		glint.modulate.a = 0.0
		glint.z_index = 1
		add_child(glint)
		_glints.append(glint)
		_glint_phase.append(float(h % 1000) / 1000.0 * TAU)


## A small 4-point white cross that reads as a spark.
func _glint_texture() -> ImageTexture:
	var img: Image = Image.create(9, 9, false, Image.FORMAT_RGBA8)
	for i: int in 9:
		var f: float = 1.0 - absf(float(i) - 4.0) / 4.0
		img.set_pixel(i, 4, Color(1, 1, 1, f))
		img.set_pixel(4, i, Color(1, 1, 1, f))
	img.set_pixel(4, 4, Color(1, 1, 1, 1))
	return ImageTexture.create_from_image(img)


## Scatter set dressing on the room's floor surfaces so the delve reads as a
## worked, lived-in mine instead of bare rock. Deferred so the generated Tiles
## layer is ready. Placement is a per-cell hash (stable across loads, and NOT
## the seeded Rng — cosmetics must never perturb gameplay streams), skips the
## entry and exit so nothing clutters the spawn or the beacon, and it is capped.
@export_group("Set dressing")
## Rough share of floor cells that get a prop, 0..100. 0 disables.
@export var dressing_percent: int = 9
## Hard cap on props per room, so a huge hall does not turn into a junkyard.
@export var dressing_max: int = 16

## Delve dressing is CEILING-ONLY on purpose. Props on the floor sat at the
## player's own depth but weren't solid, so "can I stand on this? is an enemy
## behind it?" — the walk-behind confusion Dustin flagged. Everything here hangs
## clearly overhead from the ceiling (short, so nothing dangles into the play
## space) and reads as background structure, never something you interact with.
## This is also the "denser rooms" answer that never touches the combat layout.
func _build_dressing() -> void:
	if dressing_percent <= 0:
		return
	var tiles: TileMapLayer = get_node_or_null(^"Tiles") as TileMapLayer
	if tiles == null:
		return
	var entry_x: float = entry.global_position.x
	var exit_x: float = exit_marker.global_position.x
	var placed: int = 0
	for cell: Vector2i in tiles.get_used_cells():
		if placed >= dressing_max:
			break
		# A ceiling underside: something here, open air just below it.
		if tiles.get_cell_source_id(cell + Vector2i.DOWN) != -1:
			continue
		var h: int = _cell_hash(cell.x, cell.y + 777)
		if h % 100 >= dressing_percent:
			continue
		var under: Vector2 = tiles.map_to_local(cell) + Vector2(0, 16)
		if absf(under.x - entry_x) < 70.0 or absf(under.x - exit_x) < 70.0:
			continue
		var prop: Node2D = _ceiling_prop(h)
		prop.position = under
		add_child(prop)
		placed += 1


## Kept SHORT so it stays up in the dead air and never reaches player height —
## timber brackets, a warm lantern, a stub chain. No floor-standing props.
func _ceiling_prop(h: int) -> Node2D:
	match (h / 100) % 5:
		0, 1:
			return SetDressing.make_bracket(56.0 + float(h % 40), 14.0 + float(h % 10))
		2:
			return SetDressing.make_lantern(40.0 + float(h % 30))
		_:
			return SetDressing.make_chain(28.0 + float(h % 40))


## Pick a prop from the cell hash — mostly crates and rubble, a barrel now and
## then. Rubble hugs the ground; crates and barrels sit on it.
func _dressing_prop(h: int) -> Node2D:
	match (h / 100) % 5:
		0, 1:
			return SetDressing.make_crate(40.0 + float(h % 12), 40.0 + float((h / 7) % 12))
		2:
			return SetDressing.make_barrel()
		_:
			return SetDressing.make_rubble(52.0 + float(h % 30))


## Cheap deterministic per-cell hash (matches the generator's discipline).
func _cell_hash(x: int, y: int) -> int:
	var n: int = x * 374761393 + y * 668265263 + 2246822519
	n = (n ^ (n >> 13)) * 1274126177
	return absi(n ^ (n >> 16))


## Visual only: the beacon breathes, and ore veins glint.
func _process(delta: float) -> void:
	_animate_glints()
	if _exit_shaft == null:
		return
	_pulse = fposmod(_pulse + delta * exit_pulse_hz, 1.0)
	var breath: float = 0.5 + 0.5 * sin(_pulse * TAU)
	_exit_shaft.modulate.a = 0.5 + 0.4 * breath
	if _exit_light != null:
		_exit_light.energy = 0.95 + 0.5 * breath


## Each glint is dark most of the time and spikes to a brief spark — a high
## power on a slow sine gives a sharp, occasional flash on its own phase, so no
## two veins twinkle together.
func _animate_glints() -> void:
	if _glints.is_empty():
		return
	var t: float = float(Time.get_ticks_msec()) / 1000.0
	for i: int in _glints.size():
		var s: float = 0.5 + 0.5 * sin(t * 0.9 + _glint_phase[i])
		_glints[i].modulate.a = pow(s, 7.0)


## A vertical column: opaque at the base, fading to nothing at the top.
func _shaft_texture() -> GradientTexture2D:
	var gradient: Gradient = Gradient.new()
	gradient.offsets = PackedFloat32Array([0.0, 1.0])
	gradient.colors = PackedColorArray([Color(1, 1, 1, 0), Color(1, 1, 1, 0.9)])
	var texture: GradientTexture2D = GradientTexture2D.new()
	texture.gradient = gradient
	texture.fill = GradientTexture2D.FILL_LINEAR
	texture.fill_from = Vector2(0.5, 0.0)
	texture.fill_to = Vector2(0.5, 1.0)
	texture.width = 32
	texture.height = 128
	return texture


func _glow_texture() -> GradientTexture2D:
	var gradient: Gradient = Gradient.new()
	gradient.set_color(0, Color.WHITE)
	gradient.set_color(1, Color(1, 1, 1, 0))
	var texture: GradientTexture2D = GradientTexture2D.new()
	texture.gradient = gradient
	texture.fill = GradientTexture2D.FILL_RADIAL
	texture.fill_from = Vector2(0.5, 0.5)
	texture.fill_to = Vector2(0.5, 1.0)
	texture.width = 256
	texture.height = 256
	return texture


## Lazy, not resolved in _ready — see the note in enemy.gd. A null player here
## means the exit never triggers and the run silently cannot progress.
func _get_player() -> Player:
	if _player == null or not is_instance_valid(_player):
		_player = get_tree().get_first_node_in_group(&"player") as Player
	return _player


## Spawn points, as {kind, position}. The Delve decides what to build from them,
## so rooms stay ignorant of the enemy roster.
func spawn_points() -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for child: Node in spawns.get_children():
		var marker: Marker2D = child as Marker2D
		if marker == null:
			continue
		out.append({
			"kind": String(marker.get_meta(&"kind", "grunt")),
			"position": marker.global_position,
		})
	return out


func entry_position() -> Vector2:
	return entry.global_position


func exit_position() -> Vector2:
	return exit_marker.global_position


func is_player_in_exit_zone() -> bool:
	return _in_exit_zone


func _physics_process(_delta: float) -> void:
	var player: Player = _get_player()
	if player == null:
		return
	# Only offer the choice when grounded and alive: you should not be able to
	# extract mid-jump or in a death beat.
	var inside: bool = (
		player.is_on_floor()
		and not player.is_dead()
		and player.global_position.distance_to(exit_marker.global_position) <= exit_radius
	)
	if inside != _in_exit_zone:
		_in_exit_zone = inside
		exit_zone_changed.emit(inside)
