class_name Room
extends Node2D
## A single delve room. Generated by tools/gen_rooms.gd from the ASCII maps in
## tools/rooms/room_layouts.gd — edit the maps, not these scenes.
##
## A room knows its own geometry, entry, exit and spawn points, and nothing about
## the delve it sits in. The Delve places the player and drives transitions; the
## room just answers questions. That keeps rooms reusable in any order, which is
## the whole point of assembling them from a seed.

## The player entered or left the exit zone. The run coordinator listens and puts
## up the extract/descend choice — the room itself makes no decision, it only
## reports where the player is standing.
signal exit_zone_changed(inside: bool)

@export var room_id: String = ""
@export var room_size: Vector2 = Vector2.ZERO

## Radius around the exit marker that counts as reaching it.
@export var exit_radius: float = 42.0

@export_group("Exit marker")
## The exit was an invisible trigger, so a cleared room looked like a dead end —
## you could kill everything and have no idea where to go. It is drawn, and it
## pulses, because a static rectangle reads as scenery.
@export var exit_colour: Color = Color(0.45, 0.95, 0.7)
@export var exit_size: Vector2 = Vector2(38, 76)
@export var exit_pulse_hz: float = 1.6

var _player: Player = null
var _in_exit_zone: bool = false
var _pulse: float = 0.0
var _exit_rect: ColorRect = null

@onready var entry: Marker2D = $Entry
@onready var exit_marker: Marker2D = $Exit
@onready var spawns: Node2D = $Spawns


## Built in code rather than baked into the generated scenes, so changing how the
## exit reads does not mean regenerating every room.
func _ready() -> void:
	_exit_rect = ColorRect.new()
	_exit_rect.color = exit_colour
	_exit_rect.size = exit_size
	# Sit it on the ground the marker stands on, centred horizontally.
	_exit_rect.position = Vector2(-exit_size.x * 0.5, -exit_size.y)
	exit_marker.add_child(_exit_rect)


## Visual only.
func _process(delta: float) -> void:
	if _exit_rect == null:
		return
	_pulse = fposmod(_pulse + delta * exit_pulse_hz, 1.0)
	_exit_rect.modulate.a = 0.45 + 0.35 * sin(_pulse * TAU)


## Lazy, not resolved in _ready — see the note in enemy.gd. A null player here
## means the exit never triggers and the run silently cannot progress.
func _get_player() -> Player:
	if _player == null or not is_instance_valid(_player):
		_player = get_tree().get_first_node_in_group(&"player") as Player
	return _player


## Spawn points, as {kind, position}. The Delve decides what to build from them,
## so rooms stay ignorant of the enemy roster.
func spawn_points() -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for child: Node in spawns.get_children():
		var marker: Marker2D = child as Marker2D
		if marker == null:
			continue
		out.append({
			"kind": String(marker.get_meta(&"kind", "grunt")),
			"position": marker.global_position,
		})
	return out


func entry_position() -> Vector2:
	return entry.global_position


func exit_position() -> Vector2:
	return exit_marker.global_position


func is_player_in_exit_zone() -> bool:
	return _in_exit_zone


func _physics_process(_delta: float) -> void:
	var player: Player = _get_player()
	if player == null:
		return
	# Only offer the choice when grounded and alive: you should not be able to
	# extract mid-jump or in a death beat.
	var inside: bool = (
		player.is_on_floor()
		and not player.is_dead()
		and player.global_position.distance_to(exit_marker.global_position) <= exit_radius
	)
	if inside != _in_exit_zone:
		_in_exit_zone = inside
		exit_zone_changed.emit(inside)
